//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTBC.WinExe.GetEOS
{
    using System;
    using System.Collections.Generic;
    
    public partial class TX_20450
    {
        public int SNO { get; set; }
        public Nullable<System.DateTime> cCretDT { get; set; }
        public Nullable<System.Guid> CaseId { get; set; }
        public string Account { get; set; }
        public string outputCode { get; set; }
        public string DATA1 { get; set; }
        public string DATA2 { get; set; }
        public string DATA3 { get; set; }
        public string DATA4 { get; set; }
        public string DATA5 { get; set; }
        public string DATA6 { get; set; }
        public string FIELD_07 { get; set; }
        public string FILLER5 { get; set; }
        public string FILLER6 { get; set; }
        public string FILLER7 { get; set; }
        public string TrnNum { get; set; }
        public string RepMessage { get; set; }
    }
}
