//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTBC.WinExe.GetEOS
{
    using System;
    using System.Collections.Generic;
    
    public partial class WarningGenAcct
    {
        public int id { get; set; }
        public string INST_NO { get; set; }
        public string HOME_BRCH { get; set; }
        public string ACCT_NO { get; set; }
        public string ACT_DATE_TIME { get; set; }
        public string ACT_DATE { get; set; }
        public string ACT_CCYY { get; set; }
        public string ACT_MM { get; set; }
        public string ACT_DD { get; set; }
        public string ACT_TIME { get; set; }
        public string TRAN_TYPE { get; set; }
        public string TRAN_STATUS { get; set; }
        public string TRAN_DATE { get; set; }
        public string BRANCH { get; set; }
        public string BRANCH_TERM { get; set; }
        public string TELLER { get; set; }
        public string TRAN_CODE { get; set; }
        public string POST_DATE { get; set; }
        public string JRNL_NO { get; set; }
        public string AMOUNT { get; set; }
        public string BTCH_NO_U { get; set; }
        public string CORRECTION { get; set; }
        public string DEFER_DAYS { get; set; }
        public string BALANCE { get; set; }
        public string FOREIGN_FLAG { get; set; }
        public string FILLER { get; set; }
        public string CreatedId { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public string CHQ_PAYEE { get; set; }
        public string ACCOUNT_NO { get; set; }
        public string SYSTEM { get; set; }
        public string DESCR { get; set; }
        public string DocNo { get; set; }
        public Nullable<decimal> HangAmount { get; set; }
        public string eTabs { get; set; }
        public string Memo { get; set; }
        public string TimeLog { get; set; }
        public string ModifiedUser { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string BALANCE450 { get; set; }
    }
}
