//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTBC.WinExe.AutoSeizure
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgentSetting
    {
        public int SettingId { get; set; }
        public string EmpId { get; set; }
        public string SectionName { get; set; }
        public string DepartmentID { get; set; }
        public Nullable<bool> IsSeizure { get; set; }
        public Nullable<bool> IsCase { get; set; }
    }
}
