//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTBC.WinExe.AutoSeizure
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CSFSEntities : DbContext
    {
        public CSFSEntities()
            : base("name=CSFSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CaseMaster> CaseMaster { get; set; }
        public virtual DbSet<CaseObligor> CaseObligor { get; set; }
        public virtual DbSet<TX_60629> TX_60629 { get; set; }
        public virtual DbSet<TX_60491_Detl> TX_60491_Detl { get; set; }
        public virtual DbSet<TX_60491_Grp> TX_60491_Grp { get; set; }
        public virtual DbSet<TX_60600> TX_60600 { get; set; }
        public virtual DbSet<TX_00417> TX_00417 { get; set; }
        public virtual DbSet<TX_00450> TX_00450 { get; set; }
        public virtual DbSet<TX_67002> TX_67002 { get; set; }
        public virtual DbSet<TX_67072_Detl> TX_67072_Detl { get; set; }
        public virtual DbSet<EDocTXT2> EDocTXT2 { get; set; }
        public virtual DbSet<TX_67102> TX_67102 { get; set; }
        public virtual DbSet<TX_67072_Grp> TX_67072_Grp { get; set; }
        public virtual DbSet<AutoLog> AutoLog { get; set; }
        public virtual DbSet<PARMCode> PARMCode { get; set; }
        public virtual DbSet<CaseHistory> CaseHistory { get; set; }
        public virtual DbSet<CaseMemo> CaseMemo { get; set; }
        public virtual DbSet<CaseSeizure> CaseSeizure { get; set; }
        public virtual DbSet<CaseAssignTable> CaseAssignTable { get; set; }
        public virtual DbSet<CaseSendSetting> CaseSendSetting { get; set; }
        public virtual DbSet<CaseNoTable> CaseNoTable { get; set; }
        public virtual DbSet<AgentSetting> AgentSetting { get; set; }
        public virtual DbSet<EDocTXT1> EDocTXT1 { get; set; }
        public virtual DbSet<TX_33401> TX_33401 { get; set; }
    }
}
