//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTBC.WinExe.AutoSeizure
{
    using System;
    using System.Collections.Generic;
    
    public partial class CaseAssignTable
    {
        public int AssignId { get; set; }
        public Nullable<System.Guid> CaseId { get; set; }
        public string EmpId { get; set; }
        public Nullable<int> AlreadyAssign { get; set; }
        public string CreatdUser { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedUser { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
