//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTBC.WinExe.AutoSeizure
{
    using System;
    using System.Collections.Generic;
    
    public partial class EDocTXT1
    {
        public System.Guid CaseId { get; set; }
        public string GovUnit { get; set; }
        public string GovUnitCode { get; set; }
        public System.DateTime GovDate { get; set; }
        public string ReceiverNo { get; set; }
        public string ObligorName { get; set; }
        public string Agent { get; set; }
        public string RegistrationNo { get; set; }
        public string ObligorNo { get; set; }
        public Nullable<long> Amount { get; set; }
        public Nullable<long> Fee { get; set; }
        public Nullable<long> Total { get; set; }
        public string Memo { get; set; }
        public string Unit { get; set; }
        public string Contact { get; set; }
        public string Telephone { get; set; }
    }
}
