//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTBC.WinExe.AutoSeizure
{
    using System;
    using System.Collections.Generic;
    
    public partial class TX_33401
    {
        public int SNO { get; set; }
        public string RspCode { get; set; }
        public string TrnNum { get; set; }
        public string RspMsg { get; set; }
        public string Acct { get; set; }
        public string AcctType { get; set; }
        public string MacValue { get; set; }
        public string PassbookNo { get; set; }
        public string Filler { get; set; }
        public string Name { get; set; }
        public string Currency { get; set; }
        public string InterBranch { get; set; }
        public string CustId { get; set; }
        public string AcctType2 { get; set; }
        public string AcctCat { get; set; }
        public string Branch { get; set; }
        public string Birthday { get; set; }
        public string Rate { get; set; }
        public string OpenDate { get; set; }
        public string HTel { get; set; }
        public string IntMeth { get; set; }
        public string CloseDate { get; set; }
        public string OTel { get; set; }
        public string TermDay { get; set; }
        public string IntDate { get; set; }
        public string IntAcct { get; set; }
        public string OverDate { get; set; }
        public string LastDate { get; set; }
        public string CurBal { get; set; }
        public string PbBal { get; set; }
        public string LstTax { get; set; }
        public string TodayCheck { get; set; }
        public string LonAmt { get; set; }
        public string YearAmt { get; set; }
        public string NextCheck { get; set; }
        public string TdAmt { get; set; }
        public string YearTax { get; set; }
        public string NextAmt { get; set; }
        public string HoldAmt { get; set; }
        public string OverAmt { get; set; }
        public string Micr { get; set; }
        public string IntAmt { get; set; }
        public string OverTax { get; set; }
        public string TrueAmt { get; set; }
        public string ExOdInt { get; set; }
        public string TermBasis { get; set; }
        public string AcctTypeDesc { get; set; }
        public string AtmHoldAmt { get; set; }
        public string RollCnt { get; set; }
        public string AcctStatus1 { get; set; }
        public string AcctStatus2 { get; set; }
        public string StockHoldAmt { get; set; }
        public string UnclChqUsed { get; set; }
        public string VipCode { get; set; }
        public string AssetBranch { get; set; }
        public string FB_TELLER { get; set; }
        public string ProcessStsText { get; set; }
        public string MinRepayDate { get; set; }
        public string MinRepayAmt { get; set; }
        public string HTelExt { get; set; }
        public string FaxNo { get; set; }
        public string InvestCode { get; set; }
        public string InvestType { get; set; }
        public string InvestHoldVal { get; set; }
        public string YearTaxFcy { get; set; }
        public string OtherHoldAmt { get; set; }
        public string VipDegree { get; set; }
        public string AtmWaiveExpDt { get; set; }
        public string AActDegree { get; set; }
        public string NbCusm { get; set; }
        public string CusmOrAAcDegree { get; set; }
        public string ARelationType { get; set; }
        public string SlyWaiveWdCnt { get; set; }
        public string SlyWaiveTrfCnt { get; set; }
        public string SlyStfExchgRate { get; set; }
        public string SlyOwnTrfCnt { get; set; }
        public string SlyOtherTrfCnt { get; set; }
        public string VipCDI { get; set; }
        public string HighContr { get; set; }
        public string HouseFlag { get; set; }
        public string TrialFlag { get; set; }
        public string GlobalHeadCode { get; set; }
        public string SecurityCompNo { get; set; }
        public string LgmbFlag { get; set; }
        public string OUTPUT_ERR_NO { get; set; }
        public string OUTPUT_ERR_OTHER_TXT { get; set; }
        public string BrchName { get; set; }
        public string PublishNo { get; set; }
        public string NcdAmt { get; set; }
        public string NpTfrNote { get; set; }
        public string MdHoldAmt { get; set; }
        public string PortfolioNo { get; set; }
        public string CUST_ID { get; set; }
        public Nullable<System.DateTime> cCretDT { get; set; }
        public Nullable<System.Guid> CaseId { get; set; }
    }
}
