//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTBC.WinExe.AutoSeizure
{
    using System;
    using System.Collections.Generic;
    
    public partial class TX_60491_Detl
    {
        public int SNO { get; set; }
        public int FKSNO { get; set; }
        public string Account { get; set; }
        public string Branch { get; set; }
        public string StsDesc { get; set; }
        public string ProdCode { get; set; }
        public string ProdDesc { get; set; }
        public string Link { get; set; }
        public string Ccy { get; set; }
        public string Bal { get; set; }
        public string System { get; set; }
        public string SegmentCode { get; set; }
        public string CUST_ID { get; set; }
        public Nullable<System.Guid> CaseId { get; set; }
    }
}
