//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTBC.WinExe.AutoSeizure
{
    using System;
    using System.Collections.Generic;
    
    public partial class TX_67102
    {
        public int SNO { get; set; }
        public Nullable<System.DateTime> cCretDT { get; set; }
        public Nullable<System.Guid> CaseId { get; set; }
        public string BILL_CYCLE { get; set; }
        public string BILL_DATE { get; set; }
        public string BILL_TYPE { get; set; }
        public string CIF_NO { get; set; }
        public string COMPLX_STRUCT_FLAG { get; set; }
        public string CUST_ID_NO { get; set; }
        public string CUST_NAME { get; set; }
        public string FINANC_GOODS_1 { get; set; }
        public string FINANC_GOODS_10 { get; set; }
        public string FINANC_GOODS_11 { get; set; }
        public string FINANC_GOODS_12 { get; set; }
        public string FINANC_GOODS_13 { get; set; }
        public string FINANC_GOODS_14 { get; set; }
        public string FINANC_GOODS_15 { get; set; }
        public string FINANC_GOODS_16 { get; set; }
        public string FINANC_GOODS_17 { get; set; }
        public string FINANC_GOODS_18 { get; set; }
        public string FINANC_GOODS_19 { get; set; }
        public string FINANC_GOODS_2 { get; set; }
        public string FINANC_GOODS_20 { get; set; }
        public string FINANC_GOODS_21 { get; set; }
        public string FINANC_GOODS_22 { get; set; }
        public string FINANC_GOODS_23 { get; set; }
        public string FINANC_GOODS_24 { get; set; }
        public string FINANC_GOODS_25 { get; set; }
        public string FINANC_GOODS_26 { get; set; }
        public string FINANC_GOODS_27 { get; set; }
        public string FINANC_GOODS_28 { get; set; }
        public string FINANC_GOODS_29 { get; set; }
        public string FINANC_GOODS_3 { get; set; }
        public string FINANC_GOODS_30 { get; set; }
        public string FINANC_GOODS_31 { get; set; }
        public string FINANC_GOODS_32 { get; set; }
        public string FINANC_GOODS_4 { get; set; }
        public string FINANC_GOODS_5 { get; set; }
        public string FINANC_GOODS_6 { get; set; }
        public string FINANC_GOODS_7 { get; set; }
        public string FINANC_GOODS_8 { get; set; }
        public string FINANC_GOODS_9 { get; set; }
        public string ID_TYPE { get; set; }
        public string INCOME_AMT { get; set; }
        public string MAIL_IND { get; set; }
        public string NAME_01 { get; set; }
        public string NAME_02 { get; set; }
        public string NON_REGISTER_FLAG { get; set; }
        public string REG_BIS_NO { get; set; }
        public string REG_CMPY_NO { get; set; }
        public string RESP_CUST_ID { get; set; }
        public string RESP_ID_TYPE { get; set; }
        public string RESP_NAME { get; set; }
        public string SET_PURPOSE { get; set; }
        public string SME_CORP_FLAG { get; set; }
        public string SWIFT_CODE { get; set; }
        public string TITLE_DESC_01 { get; set; }
        public string TITLE_DESC_03 { get; set; }
        public string TRAD_LIC_NO { get; set; }
        public string TrnNum { get; set; }
        public string RepMessage { get; set; }
    }
}
