//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTBC.FrameWork.HTG
{
    using System;
    using System.Collections.Generic;
    
    public partial class TX_09093
    {
        public int SNO { get; set; }
        public Nullable<System.DateTime> cCretDT { get; set; }
        public Nullable<System.Guid> CaseId { get; set; }
        public string Account { get; set; }
        public string RESPONSE_OC08 { get; set; }
        public string CURRENCY_OC08 { get; set; }
        public string CMTRASH_OC08 { get; set; }
        public string DESCRIP_OC08 { get; set; }
        public string TrnNum { get; set; }
        public string RepMessage { get; set; }
    }
}
