//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTBC.FrameWork.HTG
{
    using System;
    using System.Collections.Generic;
    
    public partial class TX_67002
    {
        public int SNO { get; set; }
        public Nullable<System.DateTime> cCretDT { get; set; }
        public Nullable<System.Guid> CaseId { get; set; }
        public string ANU_RPMT_AMT { get; set; }
        public string ANU_RPMT_CHK { get; set; }
        public string ANU_TOVR_AMT { get; set; }
        public string ANU_TOVR_CHK { get; set; }
        public string AUDT_NAME { get; set; }
        public string BASEL_LIST { get; set; }
        public string CIF_NO { get; set; }
        public string CLN_CAPT_AMT { get; set; }
        public string CLN_CAPT_CHK { get; set; }
        public string CR_RATG { get; set; }
        public string CREDIT_SCORE { get; set; }
        public string CUST_NAME { get; set; }
        public string EXTN_DPOS_AMT { get; set; }
        public string FG_CONTRACT { get; set; }
        public string FRWD_CMIT_AMT { get; set; }
        public string ID_TYPE { get; set; }
        public string LONBUS_DATE { get; set; }
        public string N_CREDIT_GRADE { get; set; }
        public string ORR_EDATE { get; set; }
        public string OTH_BANK_DESC { get; set; }
        public string OTH_BANK_OTSD_BAL { get; set; }
        public string PAL_AMT_YY_01 { get; set; }
        public string PAL_AMT_YY_01_CHK { get; set; }
        public string PAL_AMT_YY_02 { get; set; }
        public string PAL_AMT_YY_02_CHK { get; set; }
        public string PAL_AMT_YY_03 { get; set; }
        public string PAL_AMT_YY_03_CHK { get; set; }
        public string RM_NAME { get; set; }
        public string RM_NO { get; set; }
        public string SBG_NXT_RV_DT { get; set; }
        public string SBG_PRV_RV_DT { get; set; }
        public string SHDR_EQTY_AMT { get; set; }
        public string SHDR_EQTY_CHK { get; set; }
        public string SMART_FLAG { get; set; }
        public string SORD_DEBT_AMT { get; set; }
        public string SORD_DEBT_CHK { get; set; }
        public string VIP_CODE { get; set; }
        public string VIP_DEGREE { get; set; }
        public string VIP_DEGREE_FLG { get; set; }
        public string TrnNum { get; set; }
        public string RepMessage { get; set; }
    }
}
