//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTBC.WinExe.SendGSSDoc
{
    using System;
    using System.Collections.Generic;
    
    public partial class CaseCustQuery
    {
        public System.Guid NewID { get; set; }
        public string DocNo { get; set; }
        public Nullable<int> Version { get; set; }
        public Nullable<System.DateTime> RecvDate { get; set; }
        public string QFileName { get; set; }
        public string QFileName2 { get; set; }
        public string Status { get; set; }
        public string FileStatus { get; set; }
        public string AuditStatus { get; set; }
        public string UploadStatus { get; set; }
        public string ProcessingMode { get; set; }
        public Nullable<System.DateTime> CloseDate { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedUser { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedUser { get; set; }
        public string CearanceUserID { get; set; }
        public string CearanceUserName { get; set; }
        public string ROpenFileName { get; set; }
        public string RFileTransactionFileName { get; set; }
        public string ImportFormFlag { get; set; }
        public string QueryUserID { get; set; }
        public Nullable<System.DateTime> LetterDate { get; set; }
        public string LetterDeptName { get; set; }
        public string LetterNo { get; set; }
        public string Recipient { get; set; }
        public string MessageNo { get; set; }
        public Nullable<System.DateTime> MessageDate { get; set; }
        public string ImportMessage { get; set; }
        public string FileDI { get; set; }
        public string UploadUserID { get; set; }
        public string PDFStatus { get; set; }
        public string InCharge { get; set; }
        public string LetterDeptNo { get; set; }
    }
}
