//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTBC.WinExe.SendGSSDoc
{
    using System;
    using System.Collections.Generic;
    
    public partial class CaseMaster
    {
        public System.Guid CaseId { get; set; }
        public string DocNo { get; set; }
        public string Status { get; set; }
        public bool isDelete { get; set; }
        public string CaseNo { get; set; }
        public string GovKind { get; set; }
        public string GovUnit { get; set; }
        public string ReceiverNo { get; set; }
        public System.DateTime GovDate { get; set; }
        public string Speed { get; set; }
        public string ReceiveKind { get; set; }
        public string GovNo { get; set; }
        public System.DateTime LimitDate { get; set; }
        public string CaseKind { get; set; }
        public string CaseKind2 { get; set; }
        public Nullable<System.DateTime> ReceiveDate { get; set; }
        public string Unit { get; set; }
        public string Person { get; set; }
        public string AssignPerson { get; set; }
        public string CreatedUser { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedUser { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string CloseReason { get; set; }
        public Nullable<System.DateTime> ApproveDate { get; set; }
        public Nullable<System.DateTime> CloseDate { get; set; }
        public string AgentUser { get; set; }
        public string AgentBranchId { get; set; }
        public string AgentDeptId { get; set; }
        public string ApproveUser { get; set; }
        public string CloseUser { get; set; }
        public string AgentSection { get; set; }
        public string OverDueMemo { get; set; }
        public string PropertyDeclaration { get; set; }
        public string ReturnReason { get; set; }
        public bool AfterSeizureApproved { get; set; }
        public string ReturnAnswer { get; set; }
        public Nullable<System.DateTime> PayDate { get; set; }
        public Nullable<System.DateTime> AgentSubmitDate { get; set; }
        public Nullable<System.DateTime> AgentSubmitDate2 { get; set; }
        public string ApproveUser2 { get; set; }
        public Nullable<System.DateTime> ApproveDate2 { get; set; }
        public string AgentUser2 { get; set; }
        public string Receiver { get; set; }
        public Nullable<int> ReceiveAmount { get; set; }
        public Nullable<int> NotSeizureAmount { get; set; }
        public string RMUser { get; set; }
        public string HistoryStatus { get; set; }
        public string IsEnable { get; set; }
        public string OverCancel { get; set; }
        public Nullable<int> PreSubAmount { get; set; }
        public Nullable<int> PreReceiveAmount { get; set; }
        public Nullable<int> AddCharge { get; set; }
        public string PreGovNo { get; set; }
        public Nullable<System.DateTime> PreSubDate { get; set; }
    }
}
