//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTBC.WinExe.SendGSSDoc
{
    using System;
    using System.Collections.Generic;
    
    public partial class GssDoc
    {
        public int id { get; set; }
        public Nullable<int> DocType { get; set; }
        public string BatchNo { get; set; }
        public string CompanyID { get; set; }
        public string Batchmetadata { get; set; }
        public Nullable<System.DateTime> BatchDate { get; set; }
        public string TransferType { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ParserStatus { get; set; }
        public string ParserMessage { get; set; }
    }
}
