//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTBC.WinExe.SendGSSDoc
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GssEntities : DbContext
    {
        public GssEntities()
            : base("name=GssEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<GssDoc> GssDoc { get; set; }
        public virtual DbSet<GssDoc_Detail> GssDoc_Detail { get; set; }
        public virtual DbSet<CaseMaster> CaseMaster { get; set; }
        public virtual DbSet<CaseCustQuery> CaseCustQuery { get; set; }
        public virtual DbSet<CaseCustMaster> CaseCustMaster { get; set; }
    }
}
