//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTBC.WinExe.ImportWarning
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NewsEntities : DbContext
    {
        public NewsEntities()
            : base("name=NewsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<WarningGL01> WarningGL01 { get; set; }
        public virtual DbSet<WarningGL36> WarningGL36 { get; set; }
        public virtual DbSet<WarningGL20> WarningGL20 { get; set; }
        public virtual DbSet<WarningTX20480> WarningTX20480 { get; set; }
    }
}
