//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTBC.WinExe.ImportWarning
{
    using System;
    using System.Collections.Generic;
    
    public partial class WarningTX20480
    {
        public int id { get; set; }
        public string INST_NO { get; set; }
        public string ACC_NO { get; set; }
        public string REF_CODE { get; set; }
        public string STATUS { get; set; }
        public string OPEN_DATE { get; set; }
        public string LAST_UPD_DATE { get; set; }
        public string OUTSTANDING_AMT { get; set; }
        public string CreatedId { get; set; }
        public Nullable<System.DateTime> CcreatedTime { get; set; }
    }
}
