//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTBC.WinExe.SendRMEmail
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CSFS1Entities : DbContext
    {
        public CSFS1Entities()
            : base("name=CSFS1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CaseMaster> CaseMaster { get; set; }
        public virtual DbSet<CaseSeizure> CaseSeizure { get; set; }
        public virtual DbSet<TX_60491_Grp> TX_60491_Grp { get; set; }
        public virtual DbSet<PARMCode> PARMCode { get; set; }
        public virtual DbSet<PARMWorkingDay> PARMWorkingDay { get; set; }
        public virtual DbSet<CaseEdocFile> CaseEdocFile { get; set; }
        public virtual DbSet<TX_67072_Grp> TX_67072_Grp { get; set; }
    }
}
