//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTBC.WinExe.SendRMEmail
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARMCode
    {
        public int CodeUid { get; set; }
        public string CodeType { get; set; }
        public string CodeTypeDesc { get; set; }
        public string CodeNo { get; set; }
        public string CodeDesc { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public string CodeTag { get; set; }
        public string CodeMemo { get; set; }
        public Nullable<bool> Enable { get; set; }
        public string CreatedUser { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedUser { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string BANCSCode { get; set; }
        public Nullable<int> SeizureAmt { get; set; }
    }
}
