//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTBC.WinExe.ImportGSSDoc
{
    using System;
    using System.Collections.Generic;
    
    public partial class GssDoc_Detail
    {
        public int id { get; set; }
        public string BatchNo { get; set; }
        public string DocNo { get; set; }
        public string Metadata { get; set; }
        public string FileNames { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ParserStatus { get; set; }
        public string ParserMessage { get; set; }
        public string CaseKind { get; set; }
        public Nullable<System.Guid> CaseId { get; set; }
        public string SendBatchNo { get; set; }
        public Nullable<System.DateTime> SendDate { get; set; }
        public Nullable<int> SendStatus { get; set; }
        public string SendMessage { get; set; }
        public string Sendmetadata { get; set; }
    }
}
