//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTBC.FrameWork.HTG
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CSFSEntities2 : DbContext
    {
        public CSFSEntities2()
            : base("name=CSFSEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TX_00450> TX_00450 { get; set; }
        public virtual DbSet<TX_09091> TX_09091 { get; set; }
        public virtual DbSet<TX_09095> TX_09095 { get; set; }
        public virtual DbSet<TX_60600> TX_60600 { get; set; }
        public virtual DbSet<TX_60629> TX_60629 { get; set; }
        public virtual DbSet<TX_67002> TX_67002 { get; set; }
        public virtual DbSet<TX_67102> TX_67102 { get; set; }
        public virtual DbSet<TX_33401> TX_33401 { get; set; }
        public virtual DbSet<TX_60491_Detl> TX_60491_Detl { get; set; }
        public virtual DbSet<TX_60491_Grp> TX_60491_Grp { get; set; }
        public virtual DbSet<TX_67072_Detl> TX_67072_Detl { get; set; }
        public virtual DbSet<TX_67072_Grp> TX_67072_Grp { get; set; }
        public virtual DbSet<TX_00417> TX_00417 { get; set; }
        public virtual DbSet<TX_09092> TX_09092 { get; set; }
        public virtual DbSet<TX_09093> TX_09093 { get; set; }
    }
}
