//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTBC.WinExe.AutoCancel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CaseSeizure
    {
        public int SeizureId { get; set; }
        public System.Guid CaseId { get; set; }
        public Nullable<System.Guid> PayCaseId { get; set; }
        public string CaseNo { get; set; }
        public string CustId { get; set; }
        public string CustName { get; set; }
        public string BranchNo { get; set; }
        public string BranchName { get; set; }
        public string Account { get; set; }
        public string AccountStatus { get; set; }
        public string Currency { get; set; }
        public string Balance { get; set; }
        public Nullable<decimal> SeizureAmount { get; set; }
        public Nullable<decimal> ExchangeRate { get; set; }
        public Nullable<decimal> SeizureAmountNtd { get; set; }
        public Nullable<decimal> PayAmount { get; set; }
        public string SeizureStatus { get; set; }
        public string CreatedUser { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedUser { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<System.Guid> CancelCaseId { get; set; }
        public string ProdCode { get; set; }
        public string Link { get; set; }
        public string SegmentCode { get; set; }
        public Nullable<decimal> CancelAmount { get; set; }
        public Nullable<decimal> TripAmount { get; set; }
        public string OtherSeizure { get; set; }
        public Nullable<decimal> SeizureAmountSUB { get; set; }
        public string TxtStatus { get; set; }
        public Nullable<int> Seq { get; set; }
        public string TxtProdCode { get; set; }
    }
}
