//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTBC.WinExe.AutoCancel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CSFS1Entities : DbContext
    {
        public CSFS1Entities()
            : base("name=CSFS1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CaseAssignTable> CaseAssignTable { get; set; }
        public virtual DbSet<CaseHistory> CaseHistory { get; set; }
        public virtual DbSet<CaseMaster> CaseMaster { get; set; }
        public virtual DbSet<CaseMemo> CaseMemo { get; set; }
        public virtual DbSet<CaseObligor> CaseObligor { get; set; }
        public virtual DbSet<CaseSeizure> CaseSeizure { get; set; }
        public virtual DbSet<EDocTXT2> EDocTXT2 { get; set; }
        public virtual DbSet<EDocTXT1_Detail> EDocTXT1_Detail { get; set; }
        public virtual DbSet<EDocTXT2_Detail> EDocTXT2_Detail { get; set; }
        public virtual DbSet<AgentSetting> AgentSetting { get; set; }
        public virtual DbSet<PARMCode> PARMCode { get; set; }
        public virtual DbSet<EDocTXT1> EDocTXT1 { get; set; }
        public virtual DbSet<AutoLog> AutoLog { get; set; }
    }
}
