//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTBC.WinExe.AutoCancel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TX_67072_Detl
    {
        public int SNO { get; set; }
        public int FKSNO { get; set; }
        public string Branc { get; set; }
        public string LimNo { get; set; }
        public string Produ { get; set; }
        public string AppDat { get; set; }
        public string ExpDat { get; set; }
        public string Amt { get; set; }
        public string Curr { get; set; }
        public string BalAmt { get; set; }
        public string Sign { get; set; }
        public string DbbTyp { get; set; }
        public string Status { get; set; }
        public string StopCd { get; set; }
        public string HoldFlag { get; set; }
        public string APPLNO { get; set; }
        public string APPLNOB { get; set; }
        public string CUST_ID { get; set; }
        public Nullable<System.Guid> CaseId { get; set; }
    }
}
