//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTBC.WinExe.AutoCancel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TX_60600
    {
        public int SNO { get; set; }
        public Nullable<System.DateTime> cCretDT { get; set; }
        public Nullable<System.Guid> CaseId { get; set; }
        public string BR_NO { get; set; }
        public string BR_NO_1 { get; set; }
        public string BR_NO_2 { get; set; }
        public string DATA { get; set; }
        public string DATA_1 { get; set; }
        public string DATA_2 { get; set; }
        public string FIELD_NAME { get; set; }
        public string FIELD_NAME_1 { get; set; }
        public string FIELD_NAME_2 { get; set; }
        public string FILLER10_1 { get; set; }
        public string FILLER10_2 { get; set; }
        public string FILLER11 { get; set; }
        public string FILLER12 { get; set; }
        public string FILLER13 { get; set; }
        public string FILLER14 { get; set; }
        public string FILLER15 { get; set; }
        public string FILLER16 { get; set; }
        public string FILLER5_1 { get; set; }
        public string FILLER5_2 { get; set; }
        public string FILLER6_1 { get; set; }
        public string FILLER6_2 { get; set; }
        public string FILLER7_1 { get; set; }
        public string FILLER7_2 { get; set; }
        public string FILLER8_1 { get; set; }
        public string FILLER8_2 { get; set; }
        public string FILLER9_1 { get; set; }
        public string FILLER9_2 { get; set; }
        public string ITM_TYPE_1 { get; set; }
        public string ITM_TYPE_2 { get; set; }
        public string ITM_TYPE_S { get; set; }
        public string TELLER_ID { get; set; }
        public string TELLER_ID_1 { get; set; }
        public string TELLER_ID_2 { get; set; }
        public string TX_DATE { get; set; }
        public string TX_DATE_1 { get; set; }
        public string TX_DATE_2 { get; set; }
        public string TXN_NUM { get; set; }
        public string TXN_NUM_1 { get; set; }
        public string TXN_NUM_2 { get; set; }
        public string TrnNum { get; set; }
        public string RepMessage { get; set; }
    }
}
